<?php

add_action('wp_ajax_generate_crossword_pdf', 'generate_crossword_pdf_callback');
add_action('wp_ajax_nopriv_generate_crossword_pdf', 'generate_crossword_pdf_callback');

function generate_crossword_pdf_callback() {
    // Include TCPDF library (adjust the path as needed)
    include_once plugin_dir_path(__FILE__) . '/../../lib/tcpdf.php';

    // Validate and sanitize the crossword_id parameter
    if (!isset($_GET['crossword_id']) || !is_numeric($_GET['crossword_id'])) {
        wp_die(__('Invalid request.', 'wp-crossword-plugin'));
    }

    // Sanitize and cast crossword_id to integer
    $crossword_id = intval($_GET['crossword_id']);
    $showkeys = intval($_GET['show_keys']) === 1;

    // Fetch crossword data from post meta using crossword_id as post ID
    $crossword_data = get_post_meta($crossword_id, '_crossword_grid_data', true);

    if (empty($crossword_data)) {
        wp_send_json_error('No crossword data found.');
        wp_die();
    }

    // Decode JSON data to work with it as an array
    $crossword_data_array = json_decode($crossword_data, true);
    if (json_last_error() !== JSON_ERROR_NONE || !is_array($crossword_data_array)) {
        wp_send_json_error('Invalid crossword data format.');
        wp_die();
    }

    $crossword_title = get_the_title($crossword_id);

    // Define PDF filename
    $file_suffix = $showkeys ? 'keys' : 'game';
    $pdf_filename = 'crossword_' . sanitize_title($crossword_title) . '_' . $file_suffix . '.pdf';

    // PDF setup
    $pdf = new TCPDF();
    $pdf->SetCreator('Crossword Generator');
    $pdf->SetAuthor('Your Website');
    $pdf->SetTitle('Crossword Puzzle');

    // Set header and footer data
    $pdf->SetHeaderData('', 0, 'Crossword Puzzle', 'Generated by WP Crossword Plugin');
    $pdf->setHeaderFont(['helvetica', 'B', 14]);
    $pdf->setFooterFont(['helvetica', '', 10]);
    $pdf->SetMargins(15, 27, 15);
    $pdf->SetHeaderMargin(10);
    $pdf->SetFooterMargin(10);
    $pdf->SetAutoPageBreak(TRUE, 25);
    $pdf->AddPage();

    // Display the current crossword title as post title
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->Cell(0, 10, $crossword_title , 0, 1, 'C');
    $pdf->Ln(5);

    // Generate the crossword grid
    $pdf->SetFont('helvetica', '', 12);
    $html = '<div style="padding: 20px;">
                <table cellpadding="0" cellspacing="0" style="border-collapse: separate; border-spacing: 0; border: 2px solid #ccc; border-radius: 10px; overflow: hidden;">';

    $cellSize = 30;

    foreach ($crossword_data_array['grid'] as $row) {
        $html .= '<tr>';
        foreach ($row as $cell) {
            $letter = $cell['letter'];
            $clueNumber = $cell['clueNumber'];
            if ($letter !== '') {
                $cellContent = '<div style="text-align: center; font-size:12px; line-height: ' . $cellSize . 'px;">';
                
                if ($clueNumber !== '') {
                    $cellContent .= '<span style="position: absolute; top: 0px; left: 0px; font-size:8px;">' . htmlspecialchars($clueNumber) . '</span>';
                }
                
                $cellContent .= $showkeys ? htmlspecialchars($letter) : '';
                $cellContent .= '</div>';

                $html .= '<td style="width: ' . $cellSize . 'px; height: ' . $cellSize . 'px; border: 1px solid #ccc; position: relative; background-color: #d9eefa;">' . $cellContent . '</td>';
            } else {
                $html .= '<td style="width: ' . $cellSize . 'px; height: ' . $cellSize . 'px; background-color: white;"></td>';
            }
        }
        $html .= '</tr>';
    }
    $html .= '</table></div>';
    $pdf->writeHTML($html, true, false, false, false, '');

    // Clear the output buffer to prevent interference
    if (ob_get_length()) {
        ob_end_clean();
    }

    // Output the PDF and enforce the download with the correct filename
    $pdf->Output($pdf_filename, 'D');
    wp_die(); // Ensure no additional output is sent
}
